#!/usr/bin/env python3

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

AGENTS_NAMES = ("AGENTS.override.md", "AGENTS.md")
LEGACY_AGENTS_NAME = "AGENTS.local.md"
CLAUDE_NAMES = ("CLAUDE.local.md", "CLAUDE.md")
HANDOFF_NAME = "HANDOFF.md"
EXCLUDED_DIRECTORIES = {
    ".git",
    ".hg",
    ".svn",
    ".next",
    ".tox",
    ".venv",
    "build",
    "dist",
    "node_modules",
    "vendor",
    "venv",
}

AGENTS_VOLATILE = (
    (re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"), "IP address"),
    (re.compile(r"\b[0-9a-f]{7,40}\b"), "commit SHA"),
    (re.compile(r"\b20\d{2}[-./]\d{1,2}[-./]\d{1,2}\b"), "date"),
    (re.compile(r"\bocid1\.[a-z]+\.", re.IGNORECASE), "resource ID"),
)
HANDOFF_VOLATILE = AGENTS_VOLATILE + (
    (re.compile(r"\bsha(?:1|256|512)\s*:", re.IGNORECASE), "digest"),
    (
        re.compile(
            r"\b\d+\s*(?:items?|records?|rows?|processed|skipped|failed|passed|건|개)\b",
            re.IGNORECASE,
        ),
        "result count",
    ),
)
LIVE_STATE = re.compile(
    r"\bpid\b|"
    r"\b(?:server|service|process|worker|daemon)\b[^\n]{0,48}"
    r"\b(?:currently\s+)?(?:running|listening|active)\b|"
    r"\b(?:currently\s+)?(?:running|listening)\b[^\n]{0,48}"
    r"\b(?:server|service|process|worker|daemon)\b|"
    r"(?:현재|지금).*(?:실행|구동|떠\s*있|프로세스|서버)",
    re.IGNORECASE,
)
BUDGET_MARKER = re.compile(
    r"(?:≤|<=)\s*\d+\s*(?:lines?|줄)|\b\d+\s*(?:lines?|줄)\s*(?:max|maximum|이하)",
    re.IGNORECASE,
)
TOPICAL_SECTION = re.compile(
    r"^#{1,6}\s+(?:"
    r"purpose|overview|architecture|tech(?:nology)?\s+stack|features?|roadmap|"
    r"commands?|setup|implementation|status|history|recent\s+work|project\s+structure|"
    r"목적|개요|아키텍처|기술\s*스택|기능|로드맵|명령어|설치|구현|상태|이력|최근\s*작업|프로젝트\s*구조"
    r")\b",
    re.IGNORECASE,
)
TREE_CHARS = re.compile(r"[├└│]──|^\s*[├└│]")
PLACEHOLDER = re.compile(
    r"^\s*[-*]?\s*\(?(?:none|없음|n/?a|해당\s*없음)\)?\s*$", re.IGNORECASE
)
FOREIGN_BLOCK = re.compile(
    r"<!--\s*(?:BEGIN|END)\s|^#+\s*(?:Memory Bank|Auto-generated|Generated by)\b",
    re.MULTILINE | re.IGNORECASE,
)
FENCE = re.compile(r"^\s*```")
LIST_ITEM = re.compile(r"^\s*(?:[-*]|\d+[.)])\s+\S")


class Audit:
    def __init__(self, root):
        self.root = root
        self.violations = []
        self.ran = 0
        self.passed = 0
        self._git_repo = None
        self._tracked = {}

    def check(self, check_id, ok, message, file_name=None, line=None):
        self.ran += 1
        if ok:
            self.passed += 1
        else:
            self.violations.append(
                {
                    "id": check_id,
                    "file": file_name,
                    "line": line,
                    "message": message,
                }
            )
        return ok

    def relative(self, target):
        return target.relative_to(self.root).as_posix()

    def read(self, target):
        return target.read_text(encoding="utf-8", errors="replace")

    def in_git_repo(self):
        if self._git_repo is None:
            try:
                result = subprocess.run(
                    ["git", "rev-parse", "--is-inside-work-tree"],
                    cwd=self.root,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    check=False,
                )
                self._git_repo = result.returncode == 0
            except (OSError, subprocess.SubprocessError):
                self._git_repo = False
        return self._git_repo

    def tracked(self, target):
        relative = self.relative(target)
        if relative not in self._tracked:
            result = subprocess.run(
                ["git", "ls-files", "--error-unmatch", "--", relative],
                cwd=self.root,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
            self._tracked[relative] = result.returncode == 0
        return self._tracked[relative]

    def ignored(self, target):
        result = subprocess.run(
            [
                "git",
                "check-ignore",
                "--no-index",
                "--quiet",
                "--",
                self.relative(target),
            ],
            cwd=self.root,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        return result.returncode == 0


def discover(root):
    found = []
    for directory, directories, files in os.walk(str(root)):
        directories[:] = [
            name for name in directories if name not in EXCLUDED_DIRECTORIES
        ]
        base = Path(directory)
        for name in files:
            if (
                name in AGENTS_NAMES
                or name in CLAUDE_NAMES
                or name
                in {
                    LEGACY_AGENTS_NAME,
                    HANDOFF_NAME,
                }
            ):
                found.append(base / name)
    return sorted(found)


def resolve_agents_files(root, values):
    resolved = set()
    for value in values:
        target = (root / value).resolve()
        try:
            target.relative_to(root)
        except ValueError as exc:
            raise ValueError(f"AGENTS path escapes the audit root: {value}") from exc
        if target.name not in AGENTS_NAMES:
            raise ValueError(f"not an AGENTS file: {value}")
        if not target.is_file():
            raise ValueError(f"AGENTS file does not exist: {value}")
        resolved.add(target)
    return sorted(resolved)


def reviewable_lines(target):
    result = {}
    in_fence = False
    for line_number, line in enumerate(
        target.read_text(encoding="utf-8", errors="replace").splitlines(), 1
    ):
        stripped = line.strip()
        if FENCE.match(stripped):
            in_fence = not in_fence
            continue
        if in_fence or not stripped:
            continue
        result[line_number] = stripped
    return result


def file_sha256(target):
    return hashlib.sha256(target.read_bytes()).hexdigest()


def audit_semantic_review(audit, targets, review_path):
    if not targets:
        return
    if review_path is None:
        audit.check(
            "agents-review-required",
            False,
            "an independent semantic review is required for every audited AGENTS file",
        )
        return
    try:
        payload = json.loads(review_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        audit.check(
            "agents-review-invalid",
            False,
            f"cannot read semantic review: {exc}",
            str(review_path),
        )
        return
    if not isinstance(payload, dict):
        audit.check(
            "agents-review-invalid",
            False,
            "semantic review must be a JSON object",
            str(review_path),
        )
        return

    audit.check(
        "agents-review-schema",
        payload.get("schema") == 1
        and payload.get("reviewer") == "independent_subagent"
        and isinstance(payload.get("files"), list),
        "semantic review requires schema 1, an independent_subagent reviewer, and a files list",
        str(review_path),
    )
    entries = payload.get("files") if isinstance(payload.get("files"), list) else []
    by_path = {}
    duplicates = set()
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            continue
        path = entry["path"]
        if path in by_path:
            duplicates.add(path)
        by_path[path] = entry

    expected_paths = {audit.relative(target) for target in targets}
    audit.check(
        "agents-review-files",
        not duplicates and set(by_path) == expected_paths,
        "semantic review must cover exactly the AGENTS files selected for this audit",
        str(review_path),
    )

    for target in targets:
        relative = audit.relative(target)
        entry = by_path.get(relative)
        if entry is None:
            continue
        audit.check(
            "agents-review-hash",
            entry.get("sha256") == file_sha256(target),
            "semantic review does not match the final AGENTS file",
            relative,
        )
        items = entry.get("items")
        if not isinstance(items, list):
            audit.check(
                "agents-review-coverage",
                False,
                "semantic review items must cover every non-empty content line",
                relative,
            )
            continue
        reviewed = {}
        duplicate_lines = set()
        decisions_ok = True
        for item in items:
            if not isinstance(item, dict) or not isinstance(item.get("line"), int):
                decisions_ok = False
                continue
            line_number = item["line"]
            if line_number in reviewed:
                duplicate_lines.add(line_number)
            reviewed[line_number] = item.get("text")
            text = item.get("text")
            heading = isinstance(text, str) and text.startswith("#")
            valid_type = (
                item.get("memory_type") == "structure" and item.get("kind") == "heading"
                if heading
                else item.get("memory_type") == "agent_policy"
                and item.get("kind") in {"behavior", "document_pointer"}
            )
            if not valid_type or item.get("decision") != "accept":
                decisions_ok = False
        expected = reviewable_lines(target)
        audit.check(
            "agents-review-coverage",
            not duplicate_lines and reviewed == expected,
            "semantic review must cover every non-empty content line exactly once",
            relative,
        )
        audit.check(
            "agents-review-decision",
            decisions_ok,
            "every AGENTS line must be accepted as structure, agent behavior, or a document pointer",
            relative,
        )


def pattern_hits(lines, patterns):
    hits = []
    in_fence = False
    for line_number, line in enumerate(lines, 1):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        for pattern, label in patterns:
            if pattern.search(line):
                hits.append((line_number, label, line.strip()))
                break
    return hits


def audit_agents(audit, target):
    relative = audit.relative(target)
    text = audit.read(target)
    lines = text.splitlines()
    volatile = pattern_hits(lines, AGENTS_VOLATILE)
    audit.check(
        "agents-volatile",
        not volatile,
        "volatile state belongs in a durable document or nowhere: "
        + "; ".join(
            f"L{line} ({label}) {content[:60]}" for line, label, content in volatile[:6]
        ),
        relative,
        volatile[0][0] if volatile else None,
    )
    trees = [
        line for line, content in enumerate(lines, 1) if TREE_CHARS.search(content)
    ]
    audit.check(
        "agents-tree",
        not trees,
        "directory trees are project knowledge, not mandatory behavior",
        relative,
        trees[0] if trees else None,
    )
    fences = [line for line, content in enumerate(lines, 1) if FENCE.match(content)]
    audit.check(
        "agents-code-fence",
        not fences,
        "command blocks and examples belong in a scoped runbook or development document",
        relative,
        fences[0] if fences else None,
    )
    topical = [
        line for line, content in enumerate(lines, 1) if TOPICAL_SECTION.match(content)
    ]
    audit.check(
        "agents-topical-section",
        not topical,
        "planning, architecture, commands, and status belong in scoped documents",
        relative,
        topical[0] if topical else None,
    )
    audit.check(
        "foreign-block",
        not FOREIGN_BLOCK.search(text),
        "remove foreign generated banners and memory blocks",
        relative,
    )


def sections(lines):
    headings = []
    for index, line in enumerate(lines):
        if line.startswith("## "):
            headings.append((index, line[3:].strip()))
    result = {}
    for position, (start, name) in enumerate(headings):
        end = headings[position + 1][0] if position + 1 < len(headings) else len(lines)
        result.setdefault(name, []).append(lines[start + 1 : end])
    return result


def audit_handoff(audit, target):
    relative = audit.relative(target)
    text = audit.read(target)
    lines = text.splitlines()
    handoff_sections = sections(lines)
    required = {"Just done", "Next up"}
    missing = sorted(required - set(handoff_sections))
    duplicates = sorted(
        name for name, bodies in handoff_sections.items() if len(bodies) > 1
    )
    unknown = sorted(set(handoff_sections) - {"Just done", "Next up", "Blockers"})
    audit.check(
        "handoff-sections",
        not missing and not duplicates and not unknown,
        "HANDOFF must contain one Just done and one Next up section; Blockers is optional"
        + (f"; missing {missing}" if missing else "")
        + (f"; duplicate {duplicates}" if duplicates else "")
        + (f"; history sections {unknown}" if unknown else ""),
        relative,
    )
    just_done = handoff_sections.get("Just done", [[]])[0]
    just_done_items = [line for line in just_done if LIST_ITEM.match(line)]
    audit.check(
        "handoff-just-done-count",
        len(just_done_items) == 1,
        "Just done must contain exactly one outcome, not a session history",
        relative,
    )
    next_up = handoff_sections.get("Next up", [[]])[0]
    next_items = [line for line in next_up if LIST_ITEM.match(line)]
    audit.check(
        "handoff-next-up",
        bool(next_items),
        "Next up must contain at least one concrete action",
        relative,
    )
    volatile = pattern_hits(lines, HANDOFF_VOLATILE)
    audit.check(
        "handoff-volatile",
        not volatile,
        "dates, SHAs, digests, and result counts turn HANDOFF into a history log: "
        + "; ".join(
            f"L{line} ({label}) {content[:60]}" for line, label, content in volatile[:6]
        ),
        relative,
        volatile[0][0] if volatile else None,
    )
    live = [line for line, content in enumerate(lines, 1) if LIVE_STATE.search(content)]
    audit.check(
        "handoff-live-state",
        not live,
        "live process state expires too quickly for HANDOFF",
        relative,
        live[0] if live else None,
    )
    placeholders = [
        line for line, content in enumerate(lines, 1) if PLACEHOLDER.match(content)
    ]
    audit.check(
        "handoff-placeholder",
        not placeholders,
        "omit empty sections instead of writing placeholders",
        relative,
        placeholders[0] if placeholders else None,
    )
    fences = [line for line, content in enumerate(lines, 1) if FENCE.match(content)]
    audit.check(
        "handoff-code-fence",
        not fences,
        "command output does not belong in HANDOFF",
        relative,
        fences[0] if fences else None,
    )
    budget_markers = [
        line for line, content in enumerate(lines, 1) if BUDGET_MARKER.search(content)
    ]
    audit.check(
        "handoff-budget-marker",
        not budget_markers,
        "HANDOFF has no line-count budget; keep only role-relevant content",
        relative,
        budget_markers[0] if budget_markers else None,
    )


def audit_scope_imports(audit, files):
    by_directory = {}
    for target in files:
        by_directory.setdefault(target.parent, {})[target.name] = target
    for directory, names in by_directory.items():
        if LEGACY_AGENTS_NAME in names:
            relative = audit.relative(names[LEGACY_AGENTS_NAME])
            audit.check(
                "legacy-agents-local",
                False,
                "AGENTS.local.md is not loaded by Codex; migrate it to AGENTS.override.md",
                relative,
            )
        effective = None
        for name in AGENTS_NAMES:
            if name in names:
                effective = name
                break
        if effective is None:
            continue
        claude_files = [names[name] for name in CLAUDE_NAMES if name in names]
        expected = f"@{effective}"
        imported = False
        for target in claude_files:
            body = [
                line.strip() for line in audit.read(target).splitlines() if line.strip()
            ]
            if expected in body:
                imported = True
                break
        scope_name = audit.relative(directory) if directory != audit.root else "."
        audit.check(
            "claude-import",
            imported,
            f"Claude instructions for scope {scope_name} must contain a standalone {expected} import",
            audit.relative(claude_files[0]) if claude_files else scope_name,
        )


def audit_git(audit, files):
    if not audit.in_git_repo():
        return
    for target in files:
        relative = audit.relative(target)
        tracked = audit.tracked(target)
        ignored = audit.ignored(target)
        if tracked:
            audit.check(
                "gitignore-tracked",
                not ignored,
                "tracked memory is repository-owned and must not be ignored",
                relative,
            )
        else:
            audit.check(
                "gitignore-missing",
                ignored,
                "untracked local memory must be ignored by an exact or scoped pattern",
                relative,
            )


def main():
    parser = argparse.ArgumentParser(
        description="Audit AGENTS, CLAUDE, and HANDOFF role boundaries."
    )
    parser.add_argument("--root", default=".")
    parser.add_argument("--mode", choices=("routine", "full"), default="routine")
    parser.add_argument("--agents-file", action="append", default=[])
    parser.add_argument("--review-file")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"audit: {root} is not a directory", file=sys.stderr)
        return 2

    audit = Audit(root)
    files = discover(root)
    agents = [target for target in files if target.name in AGENTS_NAMES]
    handoffs = [target for target in files if target.name == HANDOFF_NAME]
    shims = [target for target in files if target.name in CLAUDE_NAMES]
    scopes = {target.parent for target in agents}

    try:
        agents_to_audit = (
            agents
            if args.mode == "full"
            else resolve_agents_files(root, args.agents_file)
        )
    except ValueError as exc:
        print(f"audit: {exc}", file=sys.stderr)
        return 2

    for target in agents_to_audit:
        audit_agents(audit, target)
    review_path = Path(args.review_file) if args.review_file else None
    if review_path is not None and not review_path.is_absolute():
        review_path = root / review_path
    if review_path is not None:
        review_path = review_path.resolve()
    audit_semantic_review(audit, agents_to_audit, review_path)
    for target in handoffs:
        audit_handoff(audit, target)
    audit_scope_imports(audit, files)
    audit_git(audit, files)

    counts = {
        "agents": len(agents),
        "handoffs": len(handoffs),
        "scopes": len(scopes),
        "shims": len(shims),
    }
    summary = "{} · AGENTS {} · HANDOFF {} · scopes {} · audit {}/{}".format(
        args.mode,
        counts["agents"],
        counts["handoffs"],
        counts["scopes"],
        audit.passed,
        audit.ran,
    )
    payload = {"summary": summary, "counts": counts, "violations": audit.violations}
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(summary)
        for violation in audit.violations:
            location = violation["file"] or "-"
            if violation.get("line"):
                location = "{}:{}".format(location, violation["line"])
            print(
                "  FAIL [{}] {} — {}".format(
                    violation["id"], location, violation["message"]
                )
            )
    return 1 if audit.violations else 0


if __name__ == "__main__":
    sys.exit(main())
