#!/usr/bin/env python3
"""Mechanical audit of session-handover files. Judgment-free checks only.

Usage: audit.py [--root DIR] [--json]
Exit: 0 clean, 1 violations found, 2 usage error.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

AGENTS_NAMES = ("AGENTS.md", "AGENTS.local.md")
SHIM_NAMES = ("CLAUDE.md", "CLAUDE.local.md")
HANDOFF_NAME = "HANDOFF.md"

AGENTS_TARGET, AGENTS_CEILING, HANDOFF_CEILING = 60, 100, 15

VOLATILE = (
    (re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"), "IP address"),
    (re.compile(r"\b[0-9a-f]{7,40}\b"), "commit SHA"),
    (re.compile(r"\bv?\d+\.\d+\.\d+\b"), "pinned version"),
    (re.compile(r"\b20\d{2}[-./]\d{1,2}[-./]\d{1,2}\b"), "date"),
    (re.compile(r"\bocid1\.[a-z]+\.", re.I), "resource ID"),
)
TREE_CHARS = re.compile(r"[├└│]──|^\s*[├└│]")
DATE_HEADER = re.compile(r"^#{1,6}\s.*\b20\d{2}[-./]\d{1,2}[-./]\d{1,2}")
PLACEHOLDER = re.compile(r"^\s*[-*]?\s*\(?(none|없음|n/?a|해당\s*없음)\)?\s*$", re.I)
FOREIGN_BLOCK = re.compile(
    r"<!--\s*(BEGIN|END)\s|^#+\s*(Memory Bank|Auto-generated|Generated by)\b", re.M | re.I
)
FENCE = re.compile(r"^\s*```")


class Audit:
    def __init__(self, root: Path):
        self.root = root
        self.violations = []
        self.ran = 0
        self.passed = 0
        self._tracked_cache = {}

    def check(self, cid, ok, msg, file=None, line=None):
        self.ran += 1
        if ok:
            self.passed += 1
        else:
            self.violations.append(
                {"id": cid, "file": file, "line": line, "message": msg}
            )
        return ok

    def read(self, name):
        p = self.root / name
        if not p.is_file():
            return None
        return p.read_text(encoding="utf-8", errors="replace")

    def present(self, names):
        for n in names:
            if (self.root / n).is_file():
                return n
        return None

    def in_git_repo(self):
        if "__repo__" not in self._tracked_cache:
            try:
                r = subprocess.run(
                    ["git", "rev-parse", "--is-inside-work-tree"],
                    cwd=self.root,
                    capture_output=True,
                )
                self._tracked_cache["__repo__"] = r.returncode == 0
            except (OSError, subprocess.SubprocessError):
                self._tracked_cache["__repo__"] = False
        return self._tracked_cache["__repo__"]

    def tracked(self, name):
        if not self.in_git_repo():
            return None
        if name not in self._tracked_cache:
            try:
                r = subprocess.run(
                    ["git", "ls-files", "--error-unmatch", name],
                    cwd=self.root,
                    capture_output=True,
                )
                self._tracked_cache[name] = r.returncode == 0
            except (OSError, subprocess.SubprocessError):
                self._tracked_cache[name] = None
        return self._tracked_cache[name]


def audit_agents(a, name):
    text = a.read(name)
    if text is None:
        return None
    lines = text.splitlines()
    n = len(lines)
    a.check(
        "budget-agents",
        n <= AGENTS_CEILING,
        f"{name} {n} lines > ceiling {AGENTS_CEILING} — prune before writing",
        name,
    )
    if AGENTS_TARGET < n <= AGENTS_CEILING:
        a.violations.append(
            {
                "id": "budget-agents-target",
                "file": name,
                "line": None,
                "message": f"{name} {n} lines > target {AGENTS_TARGET} (soft)",
                "soft": True,
            }
        )

    in_fence = False
    hits = []
    for i, line in enumerate(lines, 1):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        for rx, label in VOLATILE:
            if rx.search(line):
                hits.append((i, label, line.strip()))
                break
    a.check(
        "agents-volatile",
        not hits,
        "volatile literals — generalize or drop: "
        + "; ".join(f"L{i} ({lb}) {tx[:60]}" for i, lb, tx in hits[:6]),
        name,
        hits[0][0] if hits else None,
    )

    tree = [i for i, line in enumerate(lines, 1) if TREE_CHARS.search(line)]
    a.check(
        "agents-tree",
        not tree,
        f"directory tree at L{tree[0] if tree else 0} — rediscoverable, remove",
        name,
        tree[0] if tree else None,
    )
    a.check(
        "foreign-block",
        not FOREIGN_BLOCK.search(text),
        "foreign tool block (auto-generated banner/marker) — remove",
        name,
    )
    return n


def audit_handoff(a):
    text = a.read(HANDOFF_NAME)
    if text is None:
        return None
    lines = text.splitlines()
    n = len(lines)
    a.check(
        "budget-handoff",
        n <= HANDOFF_CEILING,
        f"{HANDOFF_NAME} {n} lines > {HANDOFF_CEILING}",
        HANDOFF_NAME,
    )
    dates = [i for i, line in enumerate(lines, 1) if DATE_HEADER.match(line)]
    a.check(
        "handoff-date-header",
        not dates,
        f"date header at L{dates[0] if dates else 0} — HANDOFF is not a log",
        HANDOFF_NAME,
        dates[0] if dates else None,
    )
    ph = [i for i, line in enumerate(lines, 1) if PLACEHOLDER.match(line)]
    a.check(
        "handoff-placeholder",
        not ph,
        f"placeholder at L{ph[0] if ph else 0} — omit the section instead",
        HANDOFF_NAME,
        ph[0] if ph else None,
    )
    a.check(
        "handoff-fence",
        not any(FENCE.match(line) for line in lines),
        "code fence — command output does not belong in HANDOFF",
        HANDOFF_NAME,
    )
    return n


def audit_shim(a, name, agents_name):
    text = a.read(name)
    if text is None:
        return
    body = [line for line in text.splitlines() if line.strip()]
    expected = f"@{agents_name}" if agents_name else "@AGENTS.md"
    a.check(
        "claude-shim",
        len(body) == 1 and body[0].strip() == expected,
        f"{name} must be exactly one line: {expected} (found {len(body)} content lines)",
        name,
    )


def audit_git(a, written):
    if not a.in_git_repo():
        return
    gi_path = a.root / ".gitignore"
    entries = set()
    if gi_path.is_file():
        entries = {
            line.strip()
            for line in gi_path.read_text(encoding="utf-8", errors="replace").splitlines()
            if line.strip() and not line.startswith("#")
        }

    for name in written:
        if a.tracked(name):
            a.check(
                "gitignore-tracked",
                name not in entries,
                f"{name} is git-tracked but listed in .gitignore — remove the entry",
                ".gitignore",
            )
        else:
            a.check(
                "gitignore-missing",
                name in entries,
                f"{name} written but not gitignored — add a whole-line entry",
                ".gitignore",
            )

    blanket = {e for e in entries if e.rstrip("/") == "docs" or e.startswith("docs/*")}
    a.check(
        "gitignore-blanket",
        not blanket,
        f"blanket docs ignore {sorted(blanket)} — list each topic doc by exact path",
        ".gitignore",
    )


def audit_upstream(a):
    for name in ("AGENTS.md", "CLAUDE.md"):
        if a.tracked(name):
            local = name.replace(".md", ".local.md")
            a.check(
                "upstream-tracked",
                (a.root / local).is_file(),
                f"{name} is upstream-tracked — write to {local} instead",
                name,
            )


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"audit: {root} is not a directory", file=sys.stderr)
        return 2

    a = Audit(root)
    agents_name = a.present(AGENTS_NAMES)
    shim_name = a.present(SHIM_NAMES)

    agents_lines = audit_agents(a, agents_name) if agents_name else None
    handoff_lines = audit_handoff(a)
    if shim_name:
        audit_shim(a, shim_name, agents_name)
    audit_upstream(a)

    written = [n for n in (agents_name, shim_name, HANDOFF_NAME) if n]
    written += [
        str(p.relative_to(root))
        for p in sorted((root / "docs").glob("*.md"))
        if (root / "docs").is_dir()
    ]
    audit_git(a, written)

    hard = [v for v in a.violations if not v.get("soft")]
    summary = " · ".join(
        filter(
            None,
            [
                f"AGENTS.md {agents_lines}줄" if agents_lines is not None else None,
                f"HANDOFF.md {handoff_lines}줄" if handoff_lines is not None else None,
                f"audit {a.passed}/{a.ran}",
            ],
        )
    )

    if args.json:
        print(json.dumps({"summary": summary, "violations": a.violations}, ensure_ascii=False, indent=2))
    else:
        print(summary)
        for v in a.violations:
            loc = f"{v['file']}:{v['line']}" if v.get("line") else (v["file"] or "-")
            mark = "warn" if v.get("soft") else "FAIL"
            print(f"  {mark} [{v['id']}] {loc} — {v['message']}")

    return 1 if hard else 0


if __name__ == "__main__":
    sys.exit(main())
